services:
  app-db:
    image: mariadb:10.5.5
    container_name: app-db
    restart: unless-stopped
    env_file: .env-db
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./MariaDB:/var/lib/mysql

  wp-db:
    image: mariadb:10.5.5
    container_name: wp-db
    restart: unless-stopped
    expose:
      - 3306
    env_file: .env-wp-db
    volumes:
      - ./App/WpManager/wordpress/MariaDB:/var/lib/mysql

  web:
    build: .
    env_file: .env
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./App:/App
    ports:
      - "8000:8000"
    depends_on:
      - selenium
      - app-db
      - redis

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  celery:
    build: .
    env_file: .env-celery
    user: django-user
    command: ["celery", "-A", "App", "worker", "--loglevel=info"]
    volumes:
      - ./App:/App
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
      - app-db
      - wp-db

  celerybeat:
    build: .
    env_file: .env-celery
    user: django-user
    command: ["celery", "-A", "App", "beat", "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    volumes:
      - ./App:/App
    depends_on:
      - redis
      - app-db

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - "4444:4444"

networks:
  default:
    external: true
    name: webproxy