services:
  $SERVICE_NAME:
    image: wordpress:latest
    container_name: $CONTAINER_NAME
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
    expose:
      - 80
      
networks:
  default:
    external: true
    name: webproxy